-- listing all the priviledges of the MySQL users
-- Granting specific privileges to 'user_0d_1'@'localhost'
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER, CREATE TABLESPACE, CREATE ROLE, DROP ROLE ON *.* TO 'user_0d_1'@'localhost';

-- Granting specific privileges to 'user_0d_2'@'localhost'
GRANT SELECT, INSERT ON user_2_db.* TO 'user_0d_2'@'localhost';

